export default {
  products: [
    {
      _id: '1',
      name: 'Mac10',
      category: 'SMG',
      image: 'client/public/images/mac-10.jpg',
      price: 60,
      brand: '',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Fit Shirt',
      category: 'SMG',
      image: '',
      price: 50,
      brand: '',
      rating: 4.2,
      numReviews: 5,
    },
    {
      _id: '3',
      name: 'Best Pants',
      category: 'AR',
      image: '',
      price: 70,
      brand: '',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Best Pants',
      category: 'AR',
      image: '',
      price: 70,
      brand: '',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: '4',
      name: 'Best Pants',
      category: 'GUNS',
      image: '',
      price: 70,
      brand: '',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
  ],
};
